server:
  port: 9080

spring:
  application:
    name: oauth2-server
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
