server:
  port: 9083
  servlet:
    context-path: /ui
security:
  oauth2:
    client:
      clientId: userservice3
      clientSecret: 9012
      accessTokenUri: http://localhost:9080/oauth/token
      userAuthorizationUri: http://localhost:9080/oauth/authorize
      scope: FOO
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjTGYegwxS7pnZIbRBZmq
          wLKhBv8HYJzOCIa+XdX9ZxqT5Nx18JE92Qeja0HGETSTu2uFZ2KCi/ukWNffIe/T
          if5NFcj0PRcEFo0vJ8CaSWpip+2DTNX6U/NA02A9nSXqhdIE3LWfXcFc0GwE+joJ
          NHGidVW4oT11X5nbENnHEF1CTacogbOlvf646+aNHpDZdr3ZZDQdkkfOrd8OFE/J
          /+EQJhYmeBECUtLCnCrgaYq8S9kZ0/syMLkuI1lAF9nQZLWb6DiB6Wbca1l+CHqc
          +OWvsvJkC5Ihd7/GHSxaTJMdOj1k01qAGS8zGkqs16lR1W70/CX/STcG4l1RlbAZ
          LwIDAQAB
          -----END PUBLIC KEY-----
spring:
  thymeleaf:
    cache: false

#logging:
#  level:
#    ROOT: DEBUG
